TECH-3517 - Adding the ability to deploy sidecar containers and attach K8s permissions to ServiceAccounts
techops-services/helm-charts pull request #41
Opened 2024-11-11 18:42 UTC by OleksandrUA

2024-11-12 01:56 UTC, sanbotto approved these changes

2024-11-12 07:20 UTC, eskp requested changes

2024-11-12 07:20 UTC, eskp commented on charts/common/values.yaml
> +sidecars: []
Curly brackets?

2024-11-12 07:20 UTC, eskp commented on charts/common/values.yaml
> +autoscaling:
Should be on the same line?

2024-11-13 12:00 UTC, eskp approved these changes

2024-11-13 12:05 UTC, merged